// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOttglSL4YU1j9wA6Vr5yDPxq6yMY5KdQ',
    appId: '1:967369894083:web:d001f4d7de6cfe93c1da76',
    messagingSenderId: '967369894083',
    projectId: 'notesapp-9292',
    authDomain: 'notesapp-9292.firebaseapp.com',
    storageBucket: 'notesapp-9292.firebasestorage.app',
    measurementId: 'G-GF9ZNECMBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9Rt4D-zror2lOZkMZxNl0RFhTAGTAqA',
    appId: '1:967369894083:android:c290c581238e87fec1da76',
    messagingSenderId: '967369894083',
    projectId: 'notesapp-9292',
    storageBucket: 'notesapp-9292.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOttglSL4YU1j9wA6Vr5yDPxq6yMY5KdQ',
    appId: '1:967369894083:web:51a28c605ae7d012c1da76',
    messagingSenderId: '967369894083',
    projectId: 'notesapp-9292',
    authDomain: 'notesapp-9292.firebaseapp.com',
    storageBucket: 'notesapp-9292.firebasestorage.app',
    measurementId: 'G-0XSFWGWH7Y',
  );

}